name: ffi_demo
version: 0.1.0
description: Learning dart:ffi
#homepage: https://example-pet-store.com/newtify
#documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ffi: ^1.0.0
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
